### ISSUE TITLE
3MF customized attributes issue

### ISSUE THREAD

**Issue by vgurav** [3MFConsortium/spec_core#24]
Problem Statement : Unable to write customized attributes by using lib3mf_model_addmetadata() API by using  3MF specification library version 1.3(lib3MF) .

Old_Version: Previously we are using3MF specification library (Lib3MFC) 1.0.1  to write attributes  with help of API lib3mf_model_addmetadata() and its write properly in 3MF file.

Now we are upgrading to library version 1.3 and its unable to write customized attributes by using lib3mf_model_addmetadata() API.
Is it require any particular format  to write attributes. If yes, Please share sample Model 3MF file having some customized attributes.

or

Is there any other way in library version 1.3 to write attributes in 3MF file.

**Comment by martinweismann** [comment]
Hi @vgurav ,

Lib3MF still supports the `lib3mf_model_getmetadatavalue` and `lib3mf_model_addmetadata` functionality (and example of the former is here):
https://github.com/3MFConsortium/lib3mf/blob/master/SDK/Examples/Source/ExtractInfo.cpp 

If you have trouble with the example, please raise an issue in the https://github.com/3MFConsortium/lib3mf repository.

One note about the versions:
the latest released version of Lib3MF (version 1.1.5 https://github.com/3MFConsortium/lib3mf/releases/tag/v1.1.5) does not yet implement the latest version 1.2.3 of the core specification (which is this repository).
The current master of Lib3MF is version 1.8.0 (will be released sometime before the end of the year), also does not yet implement version 1.2.3 of this specification.

We are working on that, though.
