### ISSUE TITLE
Review v1.2.3

### ISSUE THREAD

**Issue by martinweismann** [3MFConsortium/spec_core#27]
master currently shows v1.2.3 as pubslished, however, it is not.
1. review, whether we want to release this as is
2. if so, review the generated PDF: https://github.com/3MFConsortium/spec_core/releases/tag/untagged-970ff5534008b6c4938a

**Comment by pencerw** [comment]
this version change is small in scope, and is one that @KrisIverson called "an excellent clarification to the spec." high praise from a wise man! 

the only difference is that in 1.2.2, line 156 reads:

> ...Each part MUST use only the appropriate content type specified in Appendix C.

And in 1.2.3, it reads:

> ...Each part MUST use an appropriate content type specified in Appendix C or in an extension specification to 3MF (see [2.3.1. Support for Versioning and Extensibility]).

i would quibble with @martinweismann that the spec is "not published," but i agree with him that we should complete that process by approving the generated PDF (which looks great) ASAP.

@martinweismann, the only issue I see is with the code blocks. if you look at page 26, for instance, it appears that there's a horizontal scroll bar that (for me) is non-functional. do you know if your PDF conversion process could enable word wrap instead?

**Comment by martinweismann** [comment]
After tinkering a bit with html \<pre\>-elements lines break properly: https://github.com/3MFConsortium/spec_core/releases/tag/untagged-5eb90e80961c5e607144 

Except for two little annoyances, I am quite happy with the results:
1. lines within code-blocks break in an odd way:
![image](https://user-images.githubusercontent.com/30837766/53008319-655ec280-3439-11e9-9bb7-6d41dd68a401.png)
2. the font size is still a bit small.

@pencerw : Let me offer the following compromise regarding our nomenclature: I'll look into these two points a bit more, before we _officially release_ the already _published_ specification.

**Comment by martinweismann** [comment]
That should do:
https://github.com/3MFConsortium/spec_core/releases/tag/untagged-a9ac03b77ffba7067eda

**Comment by pencerw** [comment]
@martinweismann nomenclature seconded! and the PDF looks great to me.
