### ISSUE TITLE
Is it possible to share vertices across multiple mesh objects?

### ISSUE THREAD

**Issue by pierre-leon** [3MFConsortium/spec_core#30]
Is there any way to use one vertex buffer as a resource for all mesh objects?
The logic here is that when the output is an assembly (made of multiple objects that are fused together to form one object) there would be multiple shared vertices and the file size may grow exponentially.
![image](https://user-images.githubusercontent.com/23051249/55250911-3a8d3880-5247-11e9-8fbf-19823aba24bd.png) image from [here](https://support.stratasys.com/materials/polyjet-materials)

**Comment by martinweismann** [comment]
Hi @pierre-leon ,
as of now, it is not possible to reuse vertices from one <mesh> in another.
There are two workarounds:
a) Define a mesh for the outer shell (in your example all of the organ including the veins) that also covers the inner structure (veins) with material and color you desire. Then, define for each vein a new mesh with the desired properties. This way, the interface (and their vertices) between vein and outer organs needs to be defined only once. The rule that decides which property will win (in this case the veins' properties) is specified at the end of [this section](https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md#3431-item-element).
b) Define one mesh object that contains all shells (for outer organ hull and veins). vertices for the different shells are shared then.
