### ISSUE TITLE
Plain text version of 3MF

### ISSUE THREAD

**Issue by TomasHubelbauer** [3MFConsortium/spec_core#61]
Hi, I am currently a STL user, specifically ASCII STL. I came across 3MF and attempted to answer the question whether 3MF can be stored in a non-binary form, ideally as a folder with multiple files so that geometry data could be textual while things like thumbnail images could be say a PNG file. I failed to find any information regarding this on the spec website. Could anyone please clarify?

**Comment by bubnikv** [comment]
3MF is an implementation / extension of Open Packaging Conventions specification. 
https://en.wikipedia.org/wiki/Open_Packaging_Conventions#:~:text=The%20Open%20Packaging%20Conventions%20%28OPC%29%20is%20a%20container-file,as%20an%20Open%20XML%20Paper%20Specification%20%28OpenXPS%29%20document.

OPC is always a ZIP, however zero compression may be used.
